import { z } from "zod";
import { biInline } from "../i18n";
import { assertSafeOutboundUrl, redactUrlForOutput, safeKey } from "../security";
import type { Env } from "../types";

const COMPATIBILITY_DATE = "2026-06-27";
const PARENT_WORKER_SCRIPT_NAME = "oneaiworkers";
const RESERVED_SCRIPT_NAMES = new Set([PARENT_WORKER_SCRIPT_NAME]);

export const createChildWorkerSchema = {
  script_name: z.string().min(3).max(63).describe(biInline("Cloudflare Worker script name. Use lowercase letters, numbers and dashes.", "Назва Cloudflare Worker. Використовуйте lowercase літери, цифри й дефіси.")),
  template: z.enum(["webhook-forwarder"]).default("webhook-forwarder").describe(biInline("Safe child Worker template to deploy.", "Безпечний template дочірнього Worker для деплою.")),
  target_url: z.string().url().describe(biInline("HTTPS URL that the child Worker forwards POST/PUT/PATCH requests to, for example Make/Zapier/n8n.", "HTTPS URL, куди дочірній Worker форвардить POST/PUT/PATCH запити, наприклад Make/Zapier/n8n.")),
  description: z.string().max(500).optional().describe(biInline("Optional human-readable description.", "Опційний людський опис.")),
};

export const deployCustomChildWorkerSchema = {
  script_name: z.string().min(3).max(63).describe(biInline("Cloudflare Worker script name. Use lowercase letters, numbers and dashes.", "Назва Cloudflare Worker. Використовуйте lowercase літери, цифри й дефіси.")),
  description: z.string().min(1).max(500),
  tools: z.array(z.object({
    name: z.string().min(1).max(80),
    description: z.string().max(500).optional(),
    input_schema: z.record(z.string(), z.unknown()).optional(),
  })).min(1).max(30).describe(biInline("Tools exposed by this child Worker.", "Інструменти, які надає цей child Worker.")),
  source_code: z.string().min(20).max(120_000).describe(biInline("Custom JavaScript. It must assign exports.handlers = { toolName: async (args, env) => ... }.", "Кастомний JavaScript. Він має задати exports.handlers = { toolName: async (args, env) => ... }.")),
  allow_custom_code: z.boolean().describe(biInline("Must be true. This is a safety confirmation before deploying LLM-written code.", "Має бути true. Це підтвердження безпеки перед деплоєм коду, написаного LLM.")),
};

export async function createChildWorkerFromTemplate(env: Env, args: z.infer<z.ZodObject<typeof createChildWorkerSchema>>) {
  assertWorkerFactoryConfigured(env);

  const scriptName = normalizeScriptName(args.script_name);
  assertChildScriptName(scriptName);
  const targetUrl = assertSafeOutboundUrl(args.target_url);
  const childToken = randomToken();
  const source = childForwarderSource(targetUrl.toString(), args.description ?? biInline("Generated by OneAIWorkers", "Створено OneAIWorkers"), childToken);

  const payload = await deployModuleWorker(env, scriptName, source);
  const childTokenSecretName = await storeChildTokenOnParent(env, scriptName, childToken);
  const expectedUrl = expectedWorkersDevUrl(env, scriptName);

  return {
    script_name: scriptName,
    template: args.template,
    deployed: true,
    target_url: redactUrlForOutput(targetUrl),
    expected_workers_dev_url: expectedUrl,
    direct_access: {
      available_if_workers_dev_domain_is_enabled: Boolean(expectedUrl),
      auth_header: "x-oneaiworkers-child-token",
      intended_use: "Optional direct API access. ChatGPT should normally use the main OneAIWorkers MCP gateway instead.",
    },
    next_step: biInline(
      "The child token was stored automatically as a Cloudflare Secret on the main Worker. Save this child Worker as a connector using child_worker_token_secret. Its actions will appear as top-level OneAIWorkers MCP tools after the next tools/list refresh.",
      "Токен дочірнього Worker автоматично збережено як Cloudflare Secret в основному Worker. Збережіть дочірній Worker як конектор, використовуючи child_worker_token_secret. Його дії зʼявляться як інструменти верхнього рівня OneAIWorkers після наступного оновлення списку.",
    ),
    note: expectedUrl
      ? biInline("If the workers.dev domain is disabled or no route/domain is attached, the child URL will not work. Use a Service Binding for private production child Workers, or enable/attach a domain for protected URL mode.", "Якщо workers.dev domain вимкнений або route/domain не підключений, child URL не працюватиме. Для приватних production child Workers використовуйте Service Binding або увімкніть/підключіть domain для protected URL mode.")
      : biInline("Set CF_WORKERS_DEV_SUBDOMAIN to show the expected workers.dev URL, or use a Service Binding / Cloudflare route for this child Worker.", "Задайте CF_WORKERS_DEV_SUBDOMAIN, щоб показувати очікуваний workers.dev URL, або використовуйте Service Binding / Cloudflare route для цього child Worker."),
    child_worker_token_secret: childTokenSecretName,
    cloudflare_result: payload,
  };
}

export async function deployCustomChildWorker(env: Env, args: z.infer<z.ZodObject<typeof deployCustomChildWorkerSchema>>) {
  assertWorkerFactoryConfigured(env);
  if (!args.allow_custom_code) {
    throw new Error(biInline("Custom child Worker deploy requires explicit allow_custom_code=true.", "Деплой кастомного child Worker потребує явного allow_custom_code=true."));
  }

  const scriptName = normalizeScriptName(args.script_name);
  assertChildScriptName(scriptName);
  validateCustomSource(args.source_code);
  const childToken = randomToken();
  const source = customChildWorkerSource(args.description, args.tools, args.source_code, childToken);
  const payload = await deployModuleWorker(env, scriptName, source);
  const childTokenSecretName = await storeChildTokenOnParent(env, scriptName, childToken);
  const expectedUrl = expectedWorkersDevUrl(env, scriptName);

  return {
    script_name: scriptName,
    template: "custom-child-worker",
    deployed: true,
    expected_workers_dev_url: expectedUrl,
    child_worker_token_secret: childTokenSecretName,
    child_worker_protocol: {
      health: expectedUrl ? `${expectedUrl}/health` : "/health",
      tools_list: expectedUrl ? `${expectedUrl}/tools/list` : "/tools/list",
      tools_call: expectedUrl ? `${expectedUrl}/tools/call` : "/tools/call",
      auth_header: "x-oneaiworkers-child-token",
    },
    next_step: biInline(
      "The child token was stored automatically as a Cloudflare Secret on the main Worker. Save or refresh the connector with child_worker_token_secret set to the returned secret name.",
      "Токен дочірнього Worker автоматично збережено як Cloudflare Secret в основному Worker. Збережіть або оновіть конектор, вказавши повернену назву в child_worker_token_secret.",
    ),
    cloudflare_result: payload,
  };
}

async function storeChildTokenOnParent(env: Env, childScriptName: string, childToken: string): Promise<string> {
  const secretName = `CHILD_${childScriptName.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_TOKEN`;
  await putWorkerSecret(env, PARENT_WORKER_SCRIPT_NAME, secretName, childToken);
  return secretName;
}

async function putWorkerSecret(env: Env, scriptName: string, name: string, text: string) {
  validateSecretName(name);
  const accountId = String(env.CF_ACCOUNT_ID || "");
  const apiToken = String(env.CF_API_TOKEN || "");
  if (!accountId || !apiToken) throw new Error(biInline("Worker Builder is not configured.", "Worker Builder не налаштований."));

  const response = await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/${encodeURIComponent(scriptName)}/secrets`, {
    method: "PUT",
    headers: { authorization: `Bearer ${apiToken}`, "content-type": "application/json; charset=utf-8" },
    body: JSON.stringify({ name, text, type: "secret_text" }),
  });
  if (!response.ok) {
    throw new Error(`${biInline("Cloudflare secret API error", "Помилка Cloudflare secret API")} ${response.status}.`);
  }
  return { name, script_name: scriptName, stored: true };
}

function validateSecretName(name: string): void {
  if (!/^[A-Z][A-Z0-9_]{1,80}$/.test(name)) {
    throw new Error(biInline("Secret name must use uppercase letters, numbers, and underscores.", "Назва secret має містити великі літери, цифри й підкреслення."));
  }
}

async function deployModuleWorker(env: Env, scriptName: string, source: string) {
  const accountId = String(env.CF_ACCOUNT_ID || "");
  const apiToken = String(env.CF_API_TOKEN || "");
  if (!accountId || !apiToken) throw new Error(biInline("Worker Builder is not configured.", "Worker Builder не налаштований."));

  const form = new FormData();
  form.append(
    "metadata",
    new Blob([JSON.stringify({ main_module: "index.mjs", compatibility_date: COMPATIBILITY_DATE, usage_model: "standard" })], { type: "application/json" }),
  );
  form.append("index.mjs", new Blob([source], { type: "application/javascript+module" }), "index.mjs");

  const response = await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/${scriptName}`, {
    method: "PUT",
    headers: { authorization: `Bearer ${apiToken}` },
    body: form,
  });
  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(`${biInline("Cloudflare API error", "Помилка Cloudflare API")} ${response.status}.`);
  }
  return payload;
}

function assertWorkerFactoryConfigured(env: Env) {
  if (!env.CF_ACCOUNT_ID || !env.CF_API_TOKEN) {
    throw new Error(biInline("Worker Builder is not configured. Set CF_ACCOUNT_ID and CF_API_TOKEN first.", "Worker Builder не налаштований. Спершу задайте CF_ACCOUNT_ID і CF_API_TOKEN."));
  }
}

function normalizeScriptName(name: string): string {
  return safeKey(name).replaceAll(":", "-").replaceAll("_", "-");
}

function assertChildScriptName(scriptName: string): void {
  if (RESERVED_SCRIPT_NAMES.has(scriptName)) {
    throw new Error(biInline(
      "This script name is reserved for the main Worker.",
      "Ця назва зарезервована для основного Worker.",
    ));
  }
}

function expectedWorkersDevUrl(env: Env, scriptName: string): string | null {
  return env.CF_WORKERS_DEV_SUBDOMAIN ? `https://${scriptName}.${env.CF_WORKERS_DEV_SUBDOMAIN}.workers.dev` : null;
}

function validateCustomSource(source: string) {
  const blocked = [
    /eval\s*\(/i,
    /new\s+Function\s*\(/i,
    /WebSocket\s*\(/i,
    /connect\s*\(/i,
    /import\s*\(/i,
    /import\s+[^;]+from/i,
    /export\s+/i,
  ];
  for (const pattern of blocked) {
    if (pattern.test(source)) throw new Error(biInline("Custom source contains a blocked JavaScript pattern.", "Кастомний код містить заблокований JavaScript pattern."));
  }
  if (!source.includes("exports.handlers")) {
    throw new Error(biInline("Custom source must assign exports.handlers.", "Кастомний код має задавати exports.handlers."));
  }
}

function customChildWorkerSource(description: string, tools: unknown[], userSource: string, childToken: string): string {
  return `const DESCRIPTION = ${JSON.stringify(description)};
const TOOLS = ${JSON.stringify(tools)};
const CHILD_TOKEN = ${JSON.stringify(childToken)};
const exports = {};

${userSource}

function json(payload, status = 200) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
  });
}

function sanitize(value, env, depth = 0) {
  if (depth > 12) return "[redacted:depth-limit]";
  if (typeof value === "string") {
    let safe = value;
    const protectedValues = [CHILD_TOKEN, ...Object.values(env || {})]
      .filter((item) => typeof item === "string" && item.length >= 6);
    for (const protectedValue of protectedValues) safe = safe.split(protectedValue).join("[redacted]");
    return safe;
  }
  if (Array.isArray(value)) return value.map((item) => sanitize(item, env, depth + 1));
  if (value && typeof value === "object") {
    const output = {};
    for (const [key, child] of Object.entries(value)) {
      output[key] = /token|secret|password|authorization|api[_-]?key|cookie|signature/i.test(key)
        ? "[redacted]"
        : sanitize(child, env, depth + 1);
    }
    return output;
  }
  return value;
}

function isAuthorized(request) {
  return request.headers.get("x-oneaiworkers-child-token") === CHILD_TOKEN;
}

async function readJson(request) {
  try { return await request.json(); } catch { return {}; }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/health" && request.method === "GET") {
      return json({ ok: true, type: "oneaiworkers-child-worker", description: DESCRIPTION });
    }
    if (!isAuthorized(request)) return json({ ok: false, error: "Unauthorized" }, 401);
    if (url.pathname === "/tools/list" && request.method === "POST") {
      return json({ ok: true, tools: TOOLS });
    }
    if (url.pathname === "/tools/call" && request.method === "POST") {
      const body = await readJson(request);
      const name = String(body.name || "");
      const args = body.arguments || {};
      if (body.dry_run === true) {
        return json({ ok: true, dry_run: true, tool: name, arguments: sanitize(args, env) });
      }
      const handler = exports.handlers && exports.handlers[name];
      if (typeof handler !== "function") return json({ ok: false, error: "Tool not found" }, 404);
      try {
        const result = await handler(args, env, request);
        return json({ ok: true, data: sanitize(result, env) });
      } catch (error) {
        return json({ ok: false, error: sanitize(String(error && error.message || error), env) }, 500);
      }
    }
    return json({ ok: false, error: "Not found" }, 404);
  }
};
`;
}

function childForwarderSource(targetUrl: string, description: string, childToken: string): string {
  return `const TARGET_URL = ${JSON.stringify(targetUrl)};
const DESCRIPTION = ${JSON.stringify(description)};
const CHILD_TOKEN = ${JSON.stringify(childToken)};

function sanitizeText(value) {
  let safe = value;
  for (const protectedValue of [CHILD_TOKEN, TARGET_URL]) {
    if (protectedValue.length >= 6) safe = safe.split(protectedValue).join("[redacted]");
  }
  return safe
    .replace(/(token|secret|password|authorization|api[_-]?key)(["']?\\s*[:=]\\s*["']?)[^"',}\\s&]+/gi, "$1$2[redacted]")
    .replace(/(Bearer|Basic)\\s+[A-Za-z0-9._~+/=-]{8,}/gi, "$1 [redacted]");
}

export default {
  async fetch(request) {
    if (request.headers.get("x-oneaiworkers-child-token") !== CHILD_TOKEN) {
      return new Response(JSON.stringify({ ok: false, error: "Unauthorized" }), {
        status: 401,
        headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }
      });
    }

    if (request.method === "GET") {
      return new Response(JSON.stringify({
        ok: true,
        type: "oneaiworkers-child-worker",
        template: "webhook-forwarder",
        description: DESCRIPTION,
        message: {
          en: "Send POST, PUT, or PATCH requests to this Worker and it will forward them to the configured target URL.",
          uk: "Надсилайте POST, PUT або PATCH запити до цього Worker, і він форвардитиме їх у налаштований target URL."
        }
      }, null, 2), {
        headers: { "content-type": "application/json; charset=utf-8" }
      });
    }

    if (!["POST", "PUT", "PATCH"].includes(request.method)) {
      return new Response(JSON.stringify({ ok: false, error: { en: "Use POST, PUT, or PATCH.", uk: "Використовуйте POST, PUT або PATCH." } }), {
        status: 405,
        headers: { "content-type": "application/json; charset=utf-8" }
      });
    }

    const headers = new Headers();
    const contentType = request.headers.get("content-type");
    if (contentType) headers.set("content-type", contentType);
    headers.set("x-oneaiworkers-child", "webhook-forwarder");

    const response = await fetch(TARGET_URL, { method: request.method, headers, body: request.body, redirect: "manual" });
    return new Response(sanitizeText(await response.text()), {
      status: response.status,
      headers: { "content-type": response.headers.get("content-type") || "application/json; charset=utf-8" }
    });
  }
};
`;
}

function randomToken(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}
